In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_iris

In [3]:
X=load_iris().data
y=load_iris().target

Exercício 1

In [4]:
# compatibilização das dimensões das duas arrays para permitir a concatenação
y_bid = y.reshape (-1,1)

# concatenação na horizontal entre as arrays
arr_concat = np.hstack ((X,y_bid))

arr_concat[:10]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ]])

In [5]:
# criação do Data Frame a partir da array concatenada

df = pd.DataFrame (arr_concat, columns = ["X1","X2","X3","X4","target"])

df.head()

X1   X2   X3   X4  target
0  5.1  3.5  1.4  0.2     0.0
1  4.9  3.0  1.4  0.2     0.0
2  4.7  3.2  1.3  0.2     0.0
3  4.6  3.1  1.5  0.2     0.0
4  5.0  3.6  1.4  0.2     0.0

Exercício 2

In [6]:
# cálculo da média de valores da coluna X2 aplicada em cada subgrupo do DataFrame, definidos pelos valores de "target" 

df.groupby (by="target") . apply (lambda a: a.X2.mean())

target
0.0    3.428
1.0    2.770
2.0    2.974
dtype: float64

Exercício 3

In [7]:
# criação de uma nova coluna "target_2" com mapeamento de valores correspondentes aos da coluna "target"
# informados através do dicionário

df["target_2"] = df.target.map ({0:"A", 1:"B" ,2:"C"})

df.head()

X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0        A
1  4.9  3.0  1.4  0.2     0.0        A
2  4.7  3.2  1.3  0.2     0.0        A
3  4.6  3.1  1.5  0.2     0.0        A
4  5.0  3.6  1.4  0.2     0.0        A

Exercício 4

In [8]:
# criação de novo dataframe filtrando o dataframe original. Condição: X1 maior que 6 ou target diferente de 2.
# OBS: ao utilizar o operador "or", retornava erro. Pesquisei a respeito e encontrei referência ao operador "|"
# espero que esteja correto :)

df1 = df[(df.X1 > 6) | (df.target!=2)]

In [9]:
# criação de novo dataframe filtrando os primeiros 15 índices do dataframe original

df2=df[:15]

In [10]:
# transformação dos dataframes em arrays, após remover a coluna target_2 em formato string

arr_df1=df1.drop("target_2",axis=1).values
arr_df2=df2.drop("target_2",axis=1).values

In [11]:
# multiplicação de arrays df1 pela transposta de df2 através da função dot

arrays_multiplicadas=np.dot(arr_df1,arr_df2.T)

In [12]:
print (arrays_multiplicadas)

[[40.26 37.49 37.03 ... 36.96 33.99 45.3 ]
 [37.49 35.01 34.49 ... 34.5  31.63 42.14]
 [37.03 34.49 34.06 ... 34.   31.26 41.66]
 ...
 [48.26 45.75 44.49 ... 44.93 40.28 52.92]
 [51.33 48.53 47.31 ... 47.68 42.87 56.34]
 [51.54 48.6  47.5  ... 47.75 43.03 56.5 ]]



Exercício 5:


In [13]:
def GerarArray (N):   
    return np.arange(0,N+1,1)
   
def Embaralhar (array):
    return np.random.choice(array,size=len(array),replace=False)

def GerarArrayRand (N):
    return np.random.randint(0,N,N)


In [14]:
arr_nova=GerarArray (10)
print ("A matriz de ",len(arr_nova), " números é: ",arr_nova)

arr_embaralhada=Embaralhar(arr_nova)
print ("A matriz embaralhada é: ",arr_embaralhada)

arr_rand=GerarArrayRand(10)
print ("Uma nova matriz embaralhada de ",len(arr_rand)," números foi criada: ",arr_rand)

A matriz de  11  números é:  [ 0  1  2  3  4  5  6  7  8  9 10]
A matriz embaralhada é:  [ 9  5  7  4 10  0  6  2  3  1  8]
Uma nova matriz embaralhada de  10  números foi criada:  [7 9 1 5 8 0 6 7 6 0]



Exercício 6:



In [15]:
def DivideDados(X,p):
    linha_div=int(np.round(X.shape[0]*p))
    X1=X[:linha_div]
    X2=X[linha_div:]
    return X1,X2

In [16]:
arr_dividir = np.random.randint(0,50,(12,4))
percentual=np.random.random()
print ("A matriz a ser dividida é: \n",arr_dividir, "\n usando o índice ",percentual)

A matriz a ser dividida é: 
 [[23 33 13 42]
 [17 48 14 32]
 [48 49 34  0]
 [16 41 41 30]
 [ 8 26 23 39]
 [41 37 38 24]
 [ 1  7  6  3]
 [14 44 12 28]
 [16 45 16 18]
 [ 5 27 39 38]
 [10 24  4 17]
 [10 20 23  8]] 
 usando o índice  0.7548231904534848


In [17]:
print ("Matriz X1: \n",DivideDados(arr_dividir,percentual)[0])
print ("Matriz_X2: \n",DivideDados(arr_dividir,percentual)[1])

Matriz X1: 
 [[23 33 13 42]
 [17 48 14 32]
 [48 49 34  0]
 [16 41 41 30]
 [ 8 26 23 39]
 [41 37 38 24]
 [ 1  7  6  3]
 [14 44 12 28]
 [16 45 16 18]]
Matriz_X2: 
 [[ 5 27 39 38]
 [10 24  4 17]
 [10 20 23  8]]
